### ISSUE TITLE
Message.get is throwing error: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by SaluguManoj** [mailosaur/mailosaur-node#68]
This is my try catch block to get the emails from sentTo mail ID:

```
try {
      // Check for a new email with the given subject in Mailosaur
      const email: any = await this.mailosaurClient.messages.get(
        data.mailosaurMailId!,
        {
          sentTo,
        },
        {
          receivedAfter: new Date(Date.now() - (waitTime*2)),
        }
      );
  
      if (email) {
        const $ = cheerio.load(email.html?.body);
        const acceptUrl = $('a:contains("ACCEPT")').attr("href");
        console.log("acceptUrl", acceptUrl);
  
        if (acceptUrl) {
          return acceptUrl;
        }
      }
    } catch (error) {
      throw new Error(`API message.get execution failed to fetch messages from ${sentTo}: ${error}`);
    }
```

We have observed that this issue does not get triggered when executing locally (in fact, we can receive the required emails), but when we run the tests on GitHub actions, we get the above error. Need help here!

**Comment by jm-mailosaur** [comment]
Hi @SaluguManoj - can you let me know what exact version of the node library you are using here?

**Comment by SaluguManoj** [comment]
I have used both 14 and 16 here and for both of these versions I am getting same error.

```
name: Run CRM UI Smoke Test

on:
  workflow_dispatch:
    inputs:
      base-url:
        description: 'Base URL for the tests'
        required: false
        default: ''

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    env:

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          npm install -D @playwright/test
          npx playwright install

      - name: Run CRM Smoke Tests
        run: npm run smoketest
```
